import "./styles/global.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TheHeader } from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "theLooks",
  description: "Generated by create by Sergio & next",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />
        {children}
        <TheFooter />
      </body>
    </html>
  );
}
